CREATE DATABASE SPMEDGROUP_KAUE;
GO

USE SPMEDGROUP_KAUE;
GO


CREATE TABLE tipoUsuario(
 idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
 nomeTipo VARCHAR(100) NOT NULL UNIQUE
);
GO

CREATE TABLE usuario(
 idUsuario INT PRIMARY KEY IDENTITY, 
 idTipoUsuario TINYINT FOREIGN KEY REFERENCES tipoUsuario(idTipoUsuario),
 nome VARCHAR(100) NOT NULL,
 email VARCHAR(256) NOT NULL UNIQUE,
 senha VARCHAR(20) NOT NULL
);
GO

CREATE TABLE especializacao(
 idEspecializacao TINYINT PRIMARY KEY IDENTITY,
 nomeEspec VARCHAR(100) NOT NULL UNIQUE
);
GO

CREATE TABLE clinica(
 idClinica SMALLINT PRIMARY KEY IDENTITY,
 nomeFantasia VARCHAR(200) NOT NULL,
 cnpj VARCHAR(20) NOT NULL UNIQUE,
 razaoSocial VARCHAR(200) NOT NULL UNIQUE,
 endereco VARCHAR(200) NOT NULL UNIQUE
);
GO

CREATE TABLE paciente(
 idPaciente INT PRIMARY KEY IDENTITY,
 idUsuario INT FOREIGN KEY REFERENCES usuario(idUsuario),
 dataNasc DATE NOT NULL,
 telefone VARCHAR(20) UNIQUE,
 rg VARCHAR(15) NOT NULL UNIQUE,
 cpf VARCHAR(15) NOT NULL UNIQUE,
 endereco VARCHAR NOT NULL
);
GO